### ISSUE TITLE
kpoint

### ISSUE THREAD

**Issue by nityasagarjena** [MTD-group/Fermi-Surface#4]
kpoint other than the provided one is not working for a monolayer system.

**Comment by ShinMaterials** [comment]
Thanks for the helpful feedback.

If the issue is with Fermi_surface.py, which is not able to digest customized kpoints file, we are working on it.
In the mean time, I hope you can generate the KPOINTS file by using Fermi_kpoints.py as uploaded.

If the issue is that code does not work even with KPOINTS file generated by our code, could you explain the issue in more detail?
